### ISSUE TITLE
Review Milestone 3 Release

### ISSUE THREAD

**Issue by tylermeathe** [tylermeathe/LightDeviceDesign#7]
Hi Dr. Palmeri, 
I didn't realize that we were supposed to add and assign our schematic and flowchart to github for your review for milestone 3, so I have just added and made a release of those deliverables for your review.

Sorry about just now adding those!
Tyler

**Comment by mlp6** [comment]
Looking good... make sure that you capture the battery in the schematic not as a battery, but as the connections you need to make to the battery!
