### ISSUE TITLE
Review PCB

### ISSUE THREAD

**Issue by tylermeathe** [tylermeathe/LightDeviceDesign#9]
Hi Matt, 

I was hoping you could review my PCB. Dr. Palmeri recently looked it over but he had mentioned the need for a 16 MHz crystal oscillator for the ATMEGA328p chip. I have never really worked with this microcontroller, so I am a little confused in where I should be placing this crystal and how it will work with the microcontroller. 

If you could give me some feedback, I would appreciate it!

Thanks,

Tyler

**Comment by sphaerobolus** [comment]
All microcontrollers need a clock. The clock sort of "turns the crank" to make the microcontroller work; almost everything that happens, happens on a clock tick. 

The Uno board has a crystal oscillator for its clock. If you want your ATMega328 to work off the Uno board, you need to provide a a crystal. The crystal connects between pins 9 and 10 of the '328. You'll also need a small capacitor to ground on each of the crystal pins. Check this out:

https://www.arduino.cc/en/Tutorial/ArduinoToBreadboard

**Comment by tylermeathe** [comment]
@sphaerobolus 
Hi Matt,

I am trying to look for the library for the 9B-16.000MEEJ-B crystal, but I am not seeing it anywhere for download. Do you have this library to share with me?

**Comment by sphaerobolus** [comment]
In the Crystal library, there's HC49/S. That's the right size and thus is good enough.

**Comment by tylermeathe** [comment]
I've updated my pcb to have all of the new components if you want to take a look. Let me know if this looks good!

![image](https://user-images.githubusercontent.com/37547052/48805052-f22f9e00-ecdb-11e8-8ef1-ce6ed6f02c59.png)

**Comment by sphaerobolus** [comment]
It does look good.
